pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-raw-message-retrieval
    secrets: [ docker_username, docker_password ]
    context: app
    dockerfile: app/Dockerfile
    registry: quay.io
    force_tag: true
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_REPO_BRANCH}
    when:
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd:latest
    environment:
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk/
      - KUBE_NAMESPACE=dq-apps-notprod
      - INSECURE_SKIP_TLS_VERIFY=true
    commands:
      - export BUCKET_NAME=$$DEV_BUCKET_NAME
      - export AWS_ACCESS_KEY_ID=$$DEV_AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$$DEV_AWS_SECRET_ACCESS_KEY
      - export KEYCLOAK_CLIENT_ID=$$DEV_KEYCLOAK_CLIENT_ID
      - export KEYCLOAK_CLIENT_SECRET=$$DEV_KEYCLOAK_CLIENT_SECRET
      - export KEYCLOAK_DISCOVERY=$$DEV_KEYCLOAK_DISCOVERY
      - kd -f kube/network-policy.yml -f kube/secret.yml -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml
    secrets:
      - KUBE_TOKEN
      - DEV_BUCKET_NAME
      - DEV_AWS_ACCESS_KEY_ID
      - DEV_AWS_SECRET_ACCESS_KEY
      - DEV_KEYCLOAK_CLIENT_ID
      - DEV_KEYCLOAK_CLIENT_SECRET
      - DEV_KEYCLOAK_DISCOVERY
    when:
      event: push