---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dq-raw-message-retrieval
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: dq-raw-message-retrieval
    spec:
      containers:
        
      - name: dq-raw-message-retrieval
        image: quay.io/ukhomeofficedigital/dq-raw-message-retrieval:{{.DRONE_COMMIT_SHA}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: dq-raw-message-retrieval
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: dq-raw-message-retrieval
                key: AWS_SECRET_ACCESS_KEY
          - name: BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: dq-raw-message-retrieval
                key: BUCKET_NAME
          - name: EXPOSED_PORT
            value: '3000'
        ports:
          - containerPort: 3000

        - name: proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy-proxy-redirect
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          env:
            - name: PROXY_SERVICE_HOST
              value: 'https://127.0.0.1'
            - name: PROXY_SERVICE_PORT
              value: '8081'
            - name: LOG_FORMAT_NAME
              value: 'json'
            - name: NAXSI_USE_DEFAULT_RULES
              value: 'FALSE'
            - name: ENABLE_UUID_PARAM
              value: 'FALSE'
            - name: PROXY_REDIRECT
              value: 'https://127.0.0.1:3000 https://$host; proxy_redirect https://{{.URL}}:10443 https://$host'
            - name: ADD_NGINX_SERVER_CFG
              value: |
                proxy_read_timeout 300s;
                proxy_send_timeout 300s;
                proxy_connect_timeout 300s;
                proxy_set_header  X-Real-IP $remote_addr;
                proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header  X-Forwarded-Host $server_name;
                proxy_set_header  X-Forwarded-Proto https;
          ports:
            - name: https
              containerPort: 10443
