---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dq-raw-message-retrieval
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dq-raw-message-retrieval
    spec:
      containers:
      - name: dq-raw-message-retrieval
        image: quay.io/ukhomeofficedigital/dq-raw-message-retrieval:{{.DRONE_COMMIT_SHA}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        ports:
          - name: app_http
            containerPort: 3000
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: awscreds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: awscreds
                key: AWS_SECRET_ACCESS_KEY
          - name: BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: awscreds
                key: BUCKET_NAME
      - name: keycloak-proxy
        image: quay.io/ukhomeofficedigital/go-keycloak-proxy:v2.1.0
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        args:
          - --client-id "{{.KEYCLOAK_CLIENT_ID}}"
          - --client-secret "{{.KEYCLOAK_CLIENT_SECRET}}"
          - --listen 0.0.0.0:8081
          - --discovery-url "{{.KEYCLOAK_DISCOVERY}}"
          - --upstream-url http://127.0.0.1:8000
          - --json-format
          - --resources "uri=/*"
          - --enable-logging
          - --verbose
        ports:
          - name: http
            containerPort: 8081
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8081'
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443