---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dq-raw-message-retrieval
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dq-raw-message-retrieval
    spec:
      containers:
      - name: dq-raw-message-retrieval
        image: quay.io/ukhomeofficedigital/dq-raw-message-retrieval:{{.DRONE_COMMIT_SHA}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        ports:
          - name: http
            containerPort: 3000