---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/tls-acme: "true"
  name: dq-raw-message-retrieval-ingress
spec:
  rules:
  - host: retrieve-a-raw-message.notprod.dq.homeoffice.gov.uk
    http:
      paths:
      - backend:
          serviceName: dq-raw-message-retrieval-service
          servicePort: https
        path: /
  tls:
  - hosts:
#    - retrieve-a-raw-message.notprod.dq.homeoffice.gov.uk
#    - www.retrieve-a-raw-message.notprod.dq.homeoffice.gov.uk
    secretName: external-tls