---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    stable.k8s.psg.io/kcm.provider: http
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/tls-acme: "true"
  name: dq-raw-message-retrieval-ingress
spec:
  rules:
  - host: {{.URL}}
    http:
      paths:
      - backend:
          serviceName: dq-raw-message-retrieval-service
          servicePort: https
        path: /
  tls:
  - hosts:
    - {{.URL}}
    secretName: rmr-tls
