---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dq-raw-message-retrieval-ingress
  labels:
    cert-manager.io/solver: http01
  annotations:
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/secure-backends: "false"
    kubernetes.io/ingress.class: "nginx-external"
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/whitelist-source-range: {{ .WHITELIST_RANGES }}

spec:
  tls:
  - hosts:
    - {{.URL}}
    secretName: rmr-tls-cmio
  rules:
  - host: {{.URL}}
    http:
      paths:
      - backend:
          serviceName: dq-raw-message-retrieval-service
          servicePort: keycloak
        path: /
